# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    # ...
#    base_path: "build/ckeditor"
#    js_path:   "build/ckeditor/ckeditor.js"

    base_path: "bundles/fosckeditor"
    js_path:   "bundles/fosckeditor/ckeditor.js"
    configs:
        my_config:
#            toolbar: [ ["Source", "-", "Save"], "/", ["Anchor"], "/", ["Maximize"] ],
            language: fr
    plugins:
        balloontoolbar:
            path: "bundles/fosckeditor/plugins/balloontoolbar"
            filename: "plugins.js"